# Generated by Django 3.2.15 on 2023-12-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpAttemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('otp_count', models.IntegerField(blank=True, default=0, null=True)),
                ('last_otp_date', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
