# Generated by Django 3.2.15 on 2023-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_otpattemps'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransit',
            name='qr_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='application_status',
            field=models.CharField(choices=[('S', 'Submitted'), ('C', 'Recheck'), ('L', 'Location Pending'), ('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=3),
        ),
    ]
