# Generated by Django 3.2.15 on 2023-12-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20231227_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedtimberlog',
            name='qr_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
